# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-10 01:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticateDataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(help_text='Debe tener el formato 08-8888-8888 para nacionales o 500000000000 o 100000000000', max_length=15, validators=[django.core.validators.RegexValidator('"(^[1|5]\\d{11}$)|(^\\d{2}-\\d{4}-\\d{4}$)"', message='Debe tener el formato 08-8888-8888 para nacionales o 500000000000 o 100000000000')])),
                ('expiration_datetime', models.DateTimeField()),
                ('request_datetime', models.DateTimeField(help_text="'%Y-%m-%d %H:%M:%S',   es decir  '2006-10-25 14:30:59'")),
                ('status_text', models.CharField(default='n/d', max_length=256)),
                ('status', models.IntegerField(default=0)),
                ('received_notification', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-request_datetime',),
                'permissions': (('view_authenticatedatarequest', 'Can see available Authenticate Data Request'),),
            },
        ),
    ]
