# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 10:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticateDataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(help_text='Debe tener el formato 08-8888-8888 para nacionales o 500000000000 o 100000000000', max_length=15, validators=[django.core.validators.RegexValidator('"(^[1|5]\\d{11}$)|(^\\d{2}-\\d{4}-\\d{4}$)"', message='Debe tener el formato 08-8888-8888 para nacionales o 500000000000 o 100000000000')])),
                ('expiration_datetime', models.DateTimeField()),
                ('request_datetime', models.DateTimeField(help_text="'%Y-%m-%d %H:%M:%S',   es decir  '2006-10-25 14:30:59'")),
            ],
            options={
                'ordering': ('request_datetime',),
                'permissions': (('view_authenticatedatarequest', 'Can see available Authenticate Data Request'),),
            },
        ),
        migrations.CreateModel(
            name='AuthorizationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('authorized', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('who_authorized', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_authorized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorization request',
                'verbose_name_plural': 'Authorizations request',
            },
        ),
    ]
