# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-09 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_management', '0002_auto_20190508_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizationrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='authorizationrequest',
            name='who_authorized',
        ),
        migrations.AlterModelOptions(
            name='authenticatedatarequest',
            options={'ordering': ('-request_datetime',), 'permissions': (('view_authenticatedatarequest', 'Can see available Authenticate Data Request'),)},
        ),
        migrations.DeleteModel(
            name='AuthorizationRequest',
        ),
    ]
