# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dfva_upload', '0004_auto_20190507_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('sign_document', models.TextField(blank=True, null=True)),
                ('uploaded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dfva_upload.FileUpload')),
            ],
        ),
    ]
