# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-09 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfva_sign_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesign',
            name='format',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='filesign',
            name='place',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='filesign',
            name='reason',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='filesign',
            name='resume',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
