# Generated by Django 2.2.3 on 2019-07-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_signbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='signbase',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
