# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfva_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='sign_document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
