# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfva_upload', '0002_fileupload_sign_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='resume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
